# Generated by Django 5.2.4 on 2026-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_due_date_note_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('personal', 'Kişisel'), ('work', 'İş'), ('shopping', 'Alışveriş'), ('health', 'Sağlık'), ('study', 'Eğitim'), ('other', 'Diğer')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
