# Generated by Django 5.2.4 on 2026-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
