# Generated by Django 5.2.4 on 2026-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_feedback_admin_reply_feedback_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
