# Generated by Django 5.2.4 on 2026-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_feedback_is_deleted_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
